[tool.poetry]
name = "cmakeperf"
version = "0.1.0"
description = "Measure compilation performance from cmake compilation database"
authors = ["Paul Gessinger <hello@paulgessinger.com>"]
license = "MIT"
packages = [
    { include = "cmakeperf", from = "src"  },
    
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
psutil = "^5.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
cmakeperf = "cmakeperf.cli:main"
